### ISSUE TITLE
Please bump version Idris2

### ISSUE THREAD

**Issue by mjdtdw** [timsueberkrueb/idris2-snap#1]
https://github.com/edwinb/Idris2/releases/tag/v0.1.0

**Comment by timsueberkrueb** [comment]
`v0.1.0` is now in the edge and beta channels. Note that the edge channel contains nightly builds and gets rebuild and updated automatically whenever the Idris 2 repository changes. `beta` will only contain releases or release candidates.
Please let me know if you encounter any issues!
